export const todaysUpdate = {
  title: "Market Pulse — 26 September 2026",
  summary: "NIFTY holds above 24,300 as IT and banking stocks lead gains. Read today's session recap and tomorrow's outlook.",
  pdfUrl: "/assets/todays-market-update.pdf",
}

export const foCalls = [
  {
    id: 1,
    instrument: 'NIFTY 28 AUG 24500 CE',
    underlying: 'NIFTY 50',
    segment: 'Options',
    type: 'CE',
    action: 'BUY',
    premium: 186,
    target: 248,
    stopLoss: 142,
    expiry: '28 Aug 2026',
    lotSize: 75,
    returnsPct: 33.3,
  },
  {
    id: 2,
    instrument: 'BANKNIFTY 28 AUG 52200 PE',
    underlying: 'BANK NIFTY',
    segment: 'Options',
    type: 'PE',
    action: 'BUY',
    premium: 214,
    target: 290,
    stopLoss: 168,
    expiry: '28 Aug 2026',
    lotSize: 30,
    returnsPct: 35.5,
  },
  {
    id: 3,
    instrument: 'NIFTY AUG FUT',
    underlying: 'NIFTY 50',
    segment: 'Futures',
    type: 'FUT',
    action: 'BUY',
    premium: 24340,
    target: 24780,
    stopLoss: 24090,
    expiry: '28 Aug 2026',
    lotSize: 75,
    returnsPct: 1.8,
  },
  {
    id: 4,
    instrument: 'RELIANCE AUG FUT',
    underlying: 'RELIANCE',
    segment: 'Futures',
    type: 'FUT',
    action: 'BUY',
    premium: 2948,
    target: 3120,
    stopLoss: 2860,
    expiry: '28 Aug 2026',
    lotSize: 250,
    returnsPct: 5.8,
  },
]

export const tradingCalls = [
  {
    id: 1,
    stock: 'Reliance Industries',
    symbol: 'RELIANCE',
    action: 'BUY',
    cmp: 2920,
    target: 3200,
    stopLoss: 2780,
    returnsPct: 9.6,
    timeframe: 'Short Term',
    category: 'Large Cap',
    date: '21 Aug 2026',
    status: 'Active',
    isPro: false,
  },
  {
    id: 2,
    stock: 'HDFC Bank',
    symbol: 'HDFCBANK',
    action: 'BUY',
    cmp: 1640,
    target: 1820,
    stopLoss: 1560,
    returnsPct: 11.0,
    timeframe: 'Medium Term',
    category: 'Banking',
    date: '20 Aug 2026',
    status: 'Active',
    isPro: false,
  },
  {
    id: 3,
    stock: 'State Bank of India',
    symbol: 'SBIN',
    action: 'BUY',
    cmp: 780,
    target: 870,
    stopLoss: 735,
    returnsPct: 11.5,
    timeframe: 'Short Term',
    category: 'Banking',
    date: '20 Aug 2026',
    status: 'Active',
    isPro: false,
  },
  {
    id: 4,
    stock: 'Infosys',
    symbol: 'INFY',
    action: 'SELL',
    cmp: 1890,
    target: 1650,
    stopLoss: 1980,
    returnsPct: 12.7,
    timeframe: 'Short Term',
    category: 'IT',
    date: '19 Aug 2026',
    status: 'Active',
    isPro: true,
  },
  {
    id: 5,
    stock: 'TCS',
    symbol: 'TCS',
    action: 'BUY',
    cmp: 3980,
    target: 4350,
    stopLoss: 3800,
    returnsPct: 9.3,
    timeframe: 'Medium Term',
    category: 'IT',
    date: '18 Aug 2026',
    status: 'Active',
    isPro: true,
  },
  {
    id: 6,
    stock: 'Tata Motors',
    symbol: 'TATAMOTORS',
    action: 'BUY',
    cmp: 975,
    target: 1150,
    stopLoss: 900,
    returnsPct: 17.9,
    timeframe: 'Medium Term',
    category: 'Auto',
    date: '17 Aug 2026',
    status: 'Active',
    isPro: true,
  },
  {
    id: 7,
    stock: 'ICICI Bank',
    symbol: 'ICICIBANK',
    action: 'BUY',
    cmp: 1120,
    target: 1290,
    stopLoss: 1040,
    returnsPct: 15.2,
    timeframe: 'Long Term',
    category: 'Banking',
    date: '15 Aug 2026',
    status: 'Active',
    isPro: true,
  },
  {
    id: 8,
    stock: 'Bajaj Finance',
    symbol: 'BAJFINANCE',
    action: 'BUY',
    cmp: 7100,
    target: 7850,
    stopLoss: 6750,
    returnsPct: 10.6,
    timeframe: 'Long Term',
    category: 'NBFC',
    date: '14 Aug 2026',
    status: 'Achieved',
    isPro: true,
  },
  {
    id: 9,
    stock: 'Wipro',
    symbol: 'WIPRO',
    action: 'BUY',
    cmp: 550,
    target: 630,
    stopLoss: 510,
    returnsPct: 14.5,
    timeframe: 'Medium Term',
    category: 'IT',
    date: '13 Aug 2026',
    status: 'Active',
    isPro: true,
  },
  {
    id: 10,
    stock: 'Adani Ports',
    symbol: 'ADANIPORTS',
    action: 'BUY',
    cmp: 1340,
    target: 1520,
    stopLoss: 1260,
    returnsPct: 13.4,
    timeframe: 'Medium Term',
    category: 'Infrastructure',
    date: '12 Aug 2026',
    status: 'Active',
    isPro: true,
  },
]

// Closed-trade results the RA reports after a call plays out — a separate
// admin-filled form from the active-call one above (entry/exit/outcome for
// a trade that's already done, not a live target/stop-loss to track).
export const pastPerformances = [
  {
    id: 1,
    stock: 'Tata Motors',
    symbol: 'TATAMOTORS',
    action: 'BUY',
    entryPrice: 850,
    exitPrice: 1020,
    returnsPct: 20.0,
    duration: '45 days',
    closedDate: '10 Aug 2026',
    outcome: 'Target Hit',
    isPro: false,
  },
  {
    id: 2,
    stock: 'ITC',
    symbol: 'ITC',
    action: 'BUY',
    entryPrice: 410,
    exitPrice: 468,
    returnsPct: 14.1,
    duration: '30 days',
    closedDate: '5 Aug 2026',
    outcome: 'Target Hit',
    isPro: false,
  },
  {
    id: 3,
    stock: 'Bajaj Finance',
    symbol: 'BAJFINANCE',
    action: 'SELL',
    entryPrice: 7200,
    exitPrice: 6850,
    returnsPct: 4.9,
    duration: '12 days',
    closedDate: '28 Jul 2026',
    outcome: 'Target Hit',
    isPro: true,
  },
  {
    id: 4,
    stock: 'Zomato',
    symbol: 'ZOMATO',
    action: 'BUY',
    entryPrice: 185,
    exitPrice: 172,
    returnsPct: -7.0,
    duration: '18 days',
    closedDate: '22 Jul 2026',
    outcome: 'Stop Loss Hit',
    isPro: true,
  },
  {
    id: 5,
    stock: 'Larsen & Toubro',
    symbol: 'LT',
    action: 'BUY',
    entryPrice: 3450,
    exitPrice: 3920,
    returnsPct: 13.6,
    duration: '60 days',
    closedDate: '15 Jul 2026',
    outcome: 'Target Hit',
    isPro: true,
  },
  {
    id: 6,
    stock: 'Coal India',
    symbol: 'COALINDIA',
    action: 'BUY',
    entryPrice: 460,
    exitPrice: 512,
    returnsPct: 11.3,
    duration: '25 days',
    closedDate: '8 Jul 2026',
    outcome: 'Target Hit',
    isPro: false,
  },
]

export const courses = [
  {
    id: 2,
    title: 'Technical Analysis Masterclass',
    instructor: 'Priya Sharma',
    instructorRole: 'CMT Certified Analyst',
    duration: '12h 15m',
    lessons: 48,
    level: 'Intermediate',
    rating: 4.9,
    students: 8920,
    category: 'Technical Analysis',
    isPro: true,
    thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=1600&h=900&fit=crop&auto=format',
    description: 'Deep dive into professional technical analysis — candlestick patterns, indicators, chart patterns, and live chart strategies used by market educators.',
    whatYouLearn: [
      'All major candlestick patterns',
      'Support, resistance & trendlines',
      'RSI, MACD, Bollinger Bands',
      'Chart pattern recognition',
      'Entry, exit & stop-loss strategies',
    ],
    chapters: [
      { title: 'Candlestick Patterns', duration: '1h 30m', videos: 8, free: true },
      { title: 'Support & Resistance', duration: '1h 15m', videos: 7, free: false },
      { title: 'Moving Averages', duration: '1h 00m', videos: 6, free: false },
      { title: 'Oscillators & Momentum', duration: '1h 20m', videos: 8, free: false },
      { title: 'Advanced Chart Patterns', duration: '1h 35m', videos: 10, free: false },
      { title: 'Live Chart Strategies', duration: '1h 10m', videos: 9, free: false },
    ],
  },
  {
    id: 3,
    title: 'Mutual Fund Investing Made Easy',
    instructor: 'Ankit Mehta',
    instructorRole: 'CFP & MF Distributor',
    duration: '4h 45m',
    lessons: 18,
    level: 'Beginner',
    rating: 4.7,
    students: 19870,
    category: 'Mutual Funds',
    isPro: false,
    thumbnail: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1600&h=900&fit=crop&auto=format',
    description: 'Everything you need to know about mutual funds — from SIP setup to selecting the right funds for your financial goals.',
    whatYouLearn: [
      'Types of mutual funds',
      'How to select the right fund',
      'SIP vs lumpsum investing',
      'Reading fund fact sheets',
      'Tax implications of MF investing',
    ],
    chapters: [
      { title: 'What are Mutual Funds?', duration: '48m', videos: 4, free: true },
      { title: 'Types of Mutual Funds', duration: '1h 05m', videos: 5, free: false },
      { title: 'How to Select Funds', duration: '1h 15m', videos: 5, free: false },
      { title: 'SIP vs Lumpsum Deep Dive', duration: '58m', videos: 4, free: false },
    ],
  },
  {
    id: 4,
    title: 'Options Fundamentals',
    instructor: 'Vikram Singh',
    instructorRole: 'Derivatives Trader & Educator',
    duration: '9h 20m',
    lessons: 36,
    level: 'Advanced',
    rating: 4.9,
    students: 5640,
    category: 'Derivatives',
    isPro: true,
    thumbnail: '/assets/options-fundamentals.png',
    description: 'Learn options from scratch — calls, puts, strategies like Iron Condor, Bull Call Spread, and how hedging is typically taught.',
    whatYouLearn: [
      'Options basics: calls and puts',
      'Understanding Greeks (Delta, Gamma, Theta)',
      'Basic and advanced strategies',
      'Iron Condor, Bull Call Spread',
      'Hedging portfolio with options',
    ],
    chapters: [
      { title: 'Options Basics', duration: '1h 00m', videos: 6, free: true },
      { title: 'Greeks Explained', duration: '1h 15m', videos: 7, free: false },
      { title: 'Basic Strategies', duration: '1h 30m', videos: 8, free: false },
      { title: 'Advanced Strategies', duration: '1h 35m', videos: 9, free: false },
      { title: 'Risk Management in Options', duration: '1h 20m', videos: 6, free: false },
    ],
  },
  {
    id: 5,
    title: 'Personal Finance Basics',
    instructor: 'Sonia Gupta',
    instructorRole: 'Financial Planner & Author',
    duration: '5h 10m',
    lessons: 20,
    level: 'Beginner',
    rating: 4.6,
    students: 24100,
    category: 'Personal Finance',
    isPro: false,
    thumbnail: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1600&h=900&fit=crop&auto=format',
    description: 'Build a solid financial foundation — budgeting, emergency funds, insurance planning, and long-term money habits tailored for India.',
    whatYouLearn: [
      'Budgeting with 50/30/20 rule',
      'Building an emergency fund',
      'Term life & health insurance',
      'Tax-saving investments (ELSS, PPF)',
      'Long-term money planning',
    ],
    chapters: [
      { title: 'Budgeting & Saving', duration: '52m', videos: 4, free: true },
      { title: 'Emergency Fund & Insurance', duration: '1h 05m', videos: 5, free: false },
      { title: 'Tax Planning Basics', duration: '1h 10m', videos: 5, free: false },
      { title: 'Long-term Money Planning', duration: '1h 23m', videos: 6, free: false },
    ],
  },
]

export const videos = [
  {
    id: 1,
    title: 'How to Read Candlestick Charts in 10 Minutes',
    instructor: 'Priya Sharma',
    duration: '10:24',
    views: '2.4L',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=480&h=270&fit=crop&auto=format',
    category: 'Technical Analysis',
    date: '18 Aug 2026',
    isPro: false,
  },
  {
    id: 2,
    title: 'Understanding P/E Ratio & How to Use It',
    instructor: 'Rajesh Kumar',
    duration: '14:52',
    views: '1.8L',
    thumbnail: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=480&h=270&fit=crop&auto=format',
    category: 'Fundamental Analysis',
    date: '17 Aug 2026',
    isPro: false,
  },
  {
    id: 3,
    title: 'SIP vs Lumpsum: Which is Better in 2026?',
    instructor: 'Ankit Mehta',
    duration: '18:15',
    views: '3.2L',
    thumbnail: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=480&h=270&fit=crop&auto=format',
    category: 'Mutual Funds',
    date: '15 Aug 2026',
    isPro: false,
  },
  {
    id: 4,
    title: 'How to Use Stock Screeners Effectively',
    instructor: 'Vikram Singh',
    duration: '22:40',
    views: '95K',
    thumbnail: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=480&h=270&fit=crop&auto=format',
    category: 'Tools & Research',
    date: '14 Aug 2026',
    isPro: true,
  },
  {
    id: 5,
    title: 'Budget 2026 – Impact on Stock Markets',
    instructor: 'Sonia Gupta',
    duration: '28:10',
    views: '4.5L',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=480&h=270&fit=crop&auto=format',
    category: 'Market Analysis',
    date: '12 Aug 2026',
    isPro: false,
  },
  {
    id: 6,
    title: 'Options for Beginners: Calls & Puts',
    instructor: 'Vikram Singh',
    duration: '35:20',
    views: '1.2L',
    thumbnail: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=480&h=270&fit=crop&auto=format',
    category: 'Derivatives',
    date: '10 Aug 2026',
    isPro: true,
  },
  {
    id: 7,
    title: 'How to File ITR for Stock Market Income',
    instructor: 'Sonia Gupta',
    duration: '24:55',
    views: '2.1L',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=480&h=270&fit=crop&auto=format',
    category: 'Taxation',
    date: '8 Aug 2026',
    isPro: false,
  },
  {
    id: 8,
    title: 'Sector Rotation Strategy – Pro Insights',
    instructor: 'Priya Sharma',
    duration: '31:45',
    views: '68K',
    thumbnail: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=480&h=270&fit=crop&auto=format',
    category: 'Strategy',
    date: '6 Aug 2026',
    isPro: true,
  },
]

export const testimonials = [
  {
    name: 'Arjun Patel',
    city: 'Mumbai',
    text: "The market insights are clearly explained. The course structure helped me study setups with more confidence.",
    returns: '+70%',
    initials: 'AP',
    color: 'var(--primary)',
  },
  {
    name: 'Meera Krishnan',
    city: 'Chennai',
    text: "The research notes have completely transformed my portfolio. I now know exactly when to invest and when to wait. Absolutely worth every rupee.",
    returns: '+32%',
    initials: 'MK',
    color: '#0ECB81',
  },
  {
    name: 'Rohit Agarwal',
    city: 'Delhi',
    text: "Priya's Technical Analysis Masterclass is better than any paid course I've taken elsewhere. The content quality is exceptional.",
    returns: '+48%',
    initials: 'RA',
    color: '#6366F1',
  },
  {
    name: 'Nisha Verma',
    city: 'Bangalore',
    text: "Started as a complete beginner. Within 3 months of using Shubhshree, I can read Indian market charts with much more clarity.",
    returns: '+25%',
    initials: 'NV',
    color: '#EC4899',
  },
]

// One product, "Pro (7-day free trial)" — the Free tier was removed
// 2026-10-06 (TD-054). Pricing itself (anchor/discounted price, discount %)
// comes live from GET /pricing (TD-055, admin-configurable), not from here
// — this only holds the feature list, which doesn't change per pricing update.
export const proPlan = {
  name: 'Pro',
  badge: '7-Day Free Trial',
  features: [
    'Unlimited Market Insights daily',
    'All 45+ Courses included',
    'All Video Tutorials',
    'F&O Desk (Futures & Options)',
    'Options Education Notes',
    'Portfolio Advisory (1-on-1)',
    'Priority WhatsApp Support',
    'Monthly Live Webinars',
    'Pre-IPO & NFO Analysis',
    'Tax Planning Guide',
    'Exclusive Research Reports',
    'Early access to new content',
  ],
}
